### ISSUE TITLE
Add syln

### ISSUE THREAD

**Issue by Seekladoom** [CoffeeStraw/PyonFX#44]
I found that pyonfx doesn't have a function similar to that of **syln** in Aegisub. 

syln: number of syllables on line（source of interpretation：https://web.archive.org/web/20200218142955/http://docs.aegisub.org/3.2/Automation/Karaoke_Templater/Inline_variables/）

Please consider adding this function.

Without this function, it would be very inconvenient to calculate the total number of syllables in the current line.

**Comment by CoffeeStraw** [comment]
Hi!
It should already be straightforward to compute the number of syllables in a line:
`len(line.syls)`

Since `line.syls` is a list, you can pass it to the `len` function. Moreover, using this function is already the fastest implementation, since Python keeps a counter for the number of elements in a list under the hood and `len` simply returns it (source: https://stackoverflow.com/questions/699177/python-do-python-lists-keep-a-count-for-len-or-does-it-count-for-each-call).

**Comment by Seekladoom** [comment]
Thank you!
